# Generated by Django 3.2.10 on 2023-08-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='medications',
        ),
        migrations.AddField(
            model_name='disease',
            name='preset_medications',
            field=models.ManyToManyField(blank=True, to='myApp.Medication'),
        ),
    ]
